export const SupplierServiceTypes = [
    { "name": "Catering" },
    { "name": "Photography" },
    { "name": "Videography" },
    { "name": "Decoration" },
    { "name": "Flowers" },
    { "name": "Entertainment" },
    { "name": "Music" },
    { "name": "Lighting" },
    { "name": "Sound Systems" },
    { "name": "Event Planning" },
    { "name": "Transportation" },
    { "name": "Rentals" },
    { "name": "Invitations" },
    { "name": "Favors" },
    { "name": "Cake" },
    { "name": "Hair & Makeup" },
    { "name": "Attire" },
    { "name": "Staffing" },
    { "name": "Security" },
    { "name": "Technical Support" },
    { "name": "Audio Visual" },
    { "name": "Printing" },
    { "name": "Signage" },
    { "name": "Gifts" },
    { "name": "Accommodations" },
    { "name": "Cleaning Services" },
    { "name": "Valet Services" },
    { "name": "Custom Fabrication" },
    { "name": "Graphic Design" },
    { "name": "Consulting"}
  ];
  
  export const supplierServiceTypes: string[] = SupplierServiceTypes.map(service => service.name);