export const VenueType = [
    { "name": "Anniversary Party" },
    { "name": "Annual Meet" },
    { "name": "Awarding Ceremony" },
    { "name": "Baptism Ceremony" },
    { "name": "Baptism Reception" },
    { "name": "Birthday Party" },
    { "name": "Christmas Party" },
    { "name": "Corporate Event" },
    { "name": "Debut" },
    { "name": "Engagement Party" },
    { "name": "Family Reunion" },
    { "name": "Halloween Party" },
    { "name": "Media Event" },
    { "name": "Networking Event" },
    { "name": "New Year's Eve Party" },
    { "name": "Product Launch" },
    { "name": "Religious Event" },
    { "name": "School Prom" },
    { "name": "Seminar" },
    { "name": "Symposium" },
    { "name": "Thanksgiving Party" },
    { "name": "Themed Party" },
    { "name": "Training" },
    { "name": "Wedding" },
    { "name": "Wedding Reception" },
    { "name": "Workshop" },
    { "name": "Year End Party" }
];

export const venueTypes: string[] = VenueType.map(venue => venue.name);